# This is a Docker Compose file
# Sample usage: docker compose up

volumes:
  server-vol:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind

services:
  server:
    image: node
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    command: "node index.js"
    restart: always

    ports:
      - published: 3000
        target: 3000

    volumes:
    - type: volume
      source: server-vol
      target: /usr/src/app
